# -*- coding: utf-8 -*-
"""NSYSU Soulink

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xqmU7PMl1FlE6bmtmYwDYV4qDvdcjcwp
"""

import os

from flask import Flask, request, abort
from linebot.v3 import WebhookHandler
from linebot.v3.exceptions import InvalidSignatureError
from linebot.v3.webhooks import MessageEvent, TextMessageContent
from linebot.v3.messaging import (
    Configuration, ApiClient, MessagingApi,
    ReplyMessageRequest,
    TextMessage,
    StickerMessage,
    ImageMessage,
    VideoMessage,
    LocationMessage,
    TemplateMessage,
    ConfirmTemplate, MessageAction,
    ButtonsTemplate, URIAction, LocationAction, CameraAction, CameraRollAction,
    CarouselTemplate, CarouselColumn, URIAction, PostbackAction
)

app = Flask(__name__)

configuration = Configuration(access_token=os.getenv('Line_Access_Token'))
line_handler = WebhookHandler(os.getenv('Line_Channel_Secret'))

@app.route("/callback", methods=['POST'])
def callback():
    signature = request.headers['X-Line-Signature']
    body = request.get_data(as_text=True)
    try:
        line_handler.handle(body, signature)
    except InvalidSignatureError:
        abort(400)
    return 'OK'

import google.generativeai as genai

genai.configure(api_key=os.getenv('GOOGLE_API_KEY'))
model = genai.GenerativeModel('gemini-2.0-flash')
def ask_gemini(question):
      prompt = (
        "你是一個為台灣中山大學學生設立的，溫暖、具理解心且專業的心理諮詢Line Bot，名稱是NSYSU Soulink，不用自我介紹除非使用者問你"
        "你的任務是透過文字提供心理支持與情緒陪伴，幫助使用者梳理思緒、表達感受，並提供基礎的心理健康知識與放鬆技巧"
        "你不是執業心理師，不能提供診斷或治療，但可以鼓勵使用者就醫或尋求專業協助"
        "你的語氣要溫柔、有同理心，避免使用命令式語氣，也不做價值判斷"
        "如果使用者有自傷或他傷傾向，你會溫和地提醒他可以撥打當地的心理諮詢專線，並強調他不是一個人"
        "回覆的篇幅大概在50-100字"
        f"根據以上你的設定，回覆這個使用者的對話: {question}"
    )
      response = model.generate_content(prompt)
      return response.text

@line_handler.add(MessageEvent, message=TextMessageContent)
def handle_message(event):
    with ApiClient(configuration) as api_client:
        line_bot_api = MessagingApi(api_client)

        action = event.message.text
        if action == '心理測驗':
          reply = TextMessage(text='以下為華人心理治療基金會製作的心理與性格免費評估測驗：https://www.tip.org.tw/evaluatefree，另中山大學諮健組也提供專業的心理測驗服務，若您需要，請回覆「諮商」，已獲取中山諮健組的更多資訊與連結。')
        elif action == '位置':
          reply = LocationMessage(title="中山諮商中心",address="804高雄市鼓山區中山大學行政大樓5001",latitude=22.62611651661031, longitude=120.26617734788009)
        elif action == '諮商':
           button_template = ButtonsTemplate(
            thumbnail_image_url='',
            title="中山大學諮商資訊",
            text="行政大樓5樓",
            actions=[
                URIAction(label="中山諮健組網站", uri="https://ccd-osa.nsysu.edu.tw/"),
                URIAction(label="中山諮健組Instagram", uri="https://www.instagram.com/nsysucounseling/"),
                URIAction(label="中山個別諮商申請", uri="https://ccd-osa.nsysu.edu.tw/p/412-1091-3687.php?Lang=zh-tw"),
            ]
           )
           reply = TemplateMessage(
              alt_text = '中山大學諮商資訊',
              template = button_template)
        else:
          response = ask_gemini(action) #gemini回覆
          reply = TextMessage(text=response)


        response = ask_gemini(event.message.text)
        line_bot_api.reply_message(
            ReplyMessageRequest(
                reply_token=event.reply_token,
                messages=[
                    reply
                ]
            )
        )



if __name__ == "__main__":
    app.run()

